//! Basalt memory-hard KDF profile (spec §2, `docs/basalt-tuning.md`).
//!
//! Wraps Argon2id (RFC 9106) with version-pinned parameters. Not a new primitive.

use argon2::{Algorithm, Argon2, Params as Argon2Params, Version};
use zeroize::Zeroizing;

/// Resolved Argon2id parameters for a Basalt version.
#[derive(Clone, Copy, Debug)]
pub struct Params {
    /// Memory in KiB.
    pub m_kib: u32,
    /// Iterations (time cost).
    pub t: u32,
    /// Parallelism (lanes).
    pub p: u32,
}

/// Basalt-v1 (provisional; pending device measurement — see `docs/basalt-tuning.md`).
pub const V1: Params = Params { m_kib: 65536, t: 3, p: 1 };

/// Resolve parameters for a stored `basalt_version`.
pub fn params(version: &str) -> Option<Params> {
    match version {
        crate::BASALT_VERSION_V1 => Some(V1),
        _ => None,
    }
}

/// Compute `A = Basalt(preimage, salt_c)` as a 32-byte seed.
///
/// Uses Argon2id (v1.3) with the given parameters and a fixed 32-byte output.
/// The returned buffer is zeroized on drop.
///
/// Panics if `salt_c` is shorter than Argon2's minimum (8 bytes) or if the
/// parameters are invalid. Both are caller-controlled invariants in CLASP
/// (`salt_c` is a fixed 16-byte server value; parameters come from a pinned
/// version). TODO: surface these as a `Result` once input validation lives at
/// the API boundary.
pub fn basalt(preimage: &[u8], salt_c: &[u8], p: &Params) -> Zeroizing<[u8; 32]> {
    let a2 = Argon2Params::new(p.m_kib, p.t, p.p, Some(32)).expect("valid Basalt parameters");
    let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, a2);
    let mut out = Zeroizing::new([0u8; 32]);
    argon2
        .hash_password_into(preimage, salt_c, out.as_mut())
        .expect("Argon2id hashing into a fixed 32-byte buffer");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // Small, fast parameters for correctness tests (NOT the 64 MiB V1 profile).
    const TEST: Params = Params { m_kib: 32, t: 1, p: 1 };
    // A valid 16-byte salt (Argon2 requires >= 8 bytes).
    const SALT: &[u8] = b"0123456789abcdef";

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    #[test]
    fn output_is_32_bytes() {
        assert_eq!(basalt(b"preimage", SALT, &TEST).len(), 32);
    }

    #[test]
    fn basalt_is_deterministic() {
        let a = basalt(b"pw", SALT, &TEST);
        let b = basalt(b"pw", SALT, &TEST);
        assert_eq!(a.as_ref(), b.as_ref());
    }

    #[test]
    fn basalt_differs_by_salt() {
        let a = basalt(b"pw", b"0123456789abcdef", &TEST);
        let b = basalt(b"pw", b"fedcba9876543210", &TEST);
        assert_ne!(a.as_ref(), b.as_ref());
    }

    #[test]
    fn basalt_differs_by_params() {
        let a = basalt(b"pw", SALT, &Params { m_kib: 32, t: 1, p: 1 });
        let b = basalt(b"pw", SALT, &Params { m_kib: 32, t: 2, p: 1 });
        assert_ne!(a.as_ref(), b.as_ref());
    }

    /// Characterization (regression) vector — generated by this implementation at
    /// the small `TEST` params. Guards against accidental changes to the KDF
    /// wiring (algorithm/version/output length). Argon2id correctness itself
    /// rests on the upstream-tested `argon2` crate (RFC 9106).
    #[test]
    fn golden_small_params() {
        let a = basalt(b"correct horse battery staple", SALT, &TEST);
        assert_eq!(
            hex(a.as_ref()),
            "259e55a4c6e45074ae25a230cae9ee1c7a32c9b692ca5518b702e568c89dcdff"
        );
    }

    /// Basalt-v1 (64 MiB) profile smoke test — heavy; run explicitly with
    /// `cargo test -- --ignored`.
    #[test]
    #[ignore = "heavy 64 MiB profile"]
    fn v1_profile_smoke() {
        assert_eq!(basalt(b"pw", SALT, &V1).len(), 32);
    }
}
